//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortle.PlayerMarker.Localization {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModuleSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuleSettings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tortle.PlayerMarker.Localization.ModuleSettings", typeof(ModuleSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Cleanup Duplicate Images 的當地語系化字串。
        /// </summary>
        internal static string CleanupDuplicates_Name {
            get {
                return ResourceManager.GetString("CleanupDuplicates_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} duplicates to cleanup. 的當地語系化字串。
        /// </summary>
        internal static string CleanupDuplicates_Tooltip {
            get {
                return ResourceManager.GetString("CleanupDuplicates_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Color 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerColor_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The color of the marker. 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerColor_Tooltip {
            get {
                return ResourceManager.GetString("PlayerMarkerColor_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enabled 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerEnable_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerEnable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerEnable_Tooltip {
            get {
                return ResourceManager.GetString("PlayerMarkerEnable_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom images can be placed in the module&apos;s &apos;tortle/playermarkers&apos; directory. 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerImage_Description {
            get {
                return ResourceManager.GetString("PlayerMarkerImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image: 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerImage_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerImage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The displayed marker image. 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerImage_Tooltip {
            get {
                return ResourceManager.GetString("PlayerMarkerImage_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opacity: 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerOpacity_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerOpacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The transparency of the marker. 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerOpacity_Tooltip {
            get {
                return ResourceManager.GetString("PlayerMarkerOpacity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size: 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerSize_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The size of the marker. 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerSize_Tooltip {
            get {
                return ResourceManager.GetString("PlayerMarkerSize_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vertical Offset: 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerVerticalOffset_Name {
            get {
                return ResourceManager.GetString("PlayerMarkerVerticalOffset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The vertical position of the marker. 的當地語系化字串。
        /// </summary>
        internal static string PlayerMarkerVerticalOffset_Tooltip {
            get {
                return ResourceManager.GetString("PlayerMarkerVerticalOffset_Tooltip", resourceCulture);
            }
        }
    }
}
